def setRegionToDataFrame(target_dataframe):    
    target_dataframe.loc[target_dataframe['Country'] == 'Switzerland', 'Region'] = 'Western Europe'
    target_dataframe.loc[target_dataframe['Country'] == 'Iceland', 'Region'] = 'Western Europe'
    target_dataframe.loc[target_dataframe['Country'] == 'Denmark', 'Region'] = 'Western Europe'
    target_dataframe.loc[target_dataframe['Country'] == 'Norway', 'Region'] = 'Western Europe'
    target_dataframe.loc[target_dataframe['Country'] == 'Canada', 'Region'] = 'North America'
    target_dataframe.loc[target_dataframe['Country'] == 'Finland', 'Region'] = 'Western Europe'
    target_dataframe.loc[target_dataframe['Country'] == 'Netherlands', 'Region'] = 'Western Europe'
    target_dataframe.loc[target_dataframe['Country'] == 'Sweden', 'Region'] = 'Western Europe'
    target_dataframe.loc[target_dataframe['Country'] == 'New Zealand', 'Region'] = 'Australia and New Zealand'
    target_dataframe.loc[target_dataframe['Country'] == 'Australia', 'Region'] = 'Australia and New Zealand'
    target_dataframe.loc[target_dataframe['Country'] == 'Israel', 'Region'] = 'Middle East and Northern Africa'
    target_dataframe.loc[target_dataframe['Country'] == 'Costa Rica', 'Region'] = 'Latin America and Caribbean'
    target_dataframe.loc[target_dataframe['Country'] == 'Austria', 'Region'] = 'Western Europe'
    target_dataframe.loc[target_dataframe['Country'] == 'Mexico', 'Region'] = 'Latin America and Caribbean'
    target_dataframe.loc[target_dataframe['Country'] == 'Belize', 'Region'] = 'Latin America and Caribbean'
    target_dataframe.loc[target_dataframe['Country'] == 'United States', 'Region'] = 'North America'
    target_dataframe.loc[target_dataframe['Country'] == 'Brazil', 'Region'] = 'Latin America and Caribbean'
    target_dataframe.loc[target_dataframe['Country'] == 'Luxembourg', 'Region'] = 'Western Europe'
    target_dataframe.loc[target_dataframe['Country'] == 'Ireland', 'Region'] = 'Western Europe'
    target_dataframe.loc[target_dataframe['Country'] == 'Belgium', 'Region'] = 'Western Europe'
    target_dataframe.loc[target_dataframe['Country'] == 'United Arab Emirates', 'Region'] = 'Middle East and Northern Africa'
    target_dataframe.loc[target_dataframe['Country'] == 'United Kingdom', 'Region'] = 'Western Europe'
    target_dataframe.loc[target_dataframe['Country'] == 'Oman', 'Region'] = 'Middle East and Northern Africa'
    target_dataframe.loc[target_dataframe['Country'] == 'Venezuela', 'Region'] = 'Latin America and Caribbean'
    target_dataframe.loc[target_dataframe['Country'] == 'Singapore', 'Region'] = 'Southeastern Asia'
    target_dataframe.loc[target_dataframe['Country'] == 'Panama', 'Region'] = 'Latin America and Caribbean'
    target_dataframe.loc[target_dataframe['Country'] == 'Germany', 'Region'] = 'Western Europe'
    target_dataframe.loc[target_dataframe['Country'] == 'Chile', 'Region'] = 'Latin America and Caribbean'
    target_dataframe.loc[target_dataframe['Country'] == 'Qatar', 'Region'] = 'Middle East and Northern Africa'
    target_dataframe.loc[target_dataframe['Country'] == 'France', 'Region'] = 'Western Europe'
    target_dataframe.loc[target_dataframe['Country'] == 'Argentina', 'Region'] = 'Latin America and Caribbean'
    target_dataframe.loc[target_dataframe['Country'] == 'Czech Republic', 'Region'] = 'Central and Eastern Europe'
    target_dataframe.loc[target_dataframe['Country'] == 'Uruguay', 'Region'] = 'Latin America and Caribbean'
    target_dataframe.loc[target_dataframe['Country'] == 'Colombia', 'Region'] = 'Latin America and Caribbean'
    target_dataframe.loc[target_dataframe['Country'] == 'Thailand', 'Region'] = 'Southeastern Asia'
    target_dataframe.loc[target_dataframe['Country'] == 'Saudi Arabia', 'Region'] = 'Middle East and Northern Africa'
    target_dataframe.loc[target_dataframe['Country'] == 'Spain', 'Region'] = 'Western Europe'
    target_dataframe.loc[target_dataframe['Country'] == 'Malta', 'Region'] = 'Western Europe'
    target_dataframe.loc[target_dataframe['Country'] == 'Taiwan', 'Region'] = 'Eastern Asia'
    target_dataframe.loc[target_dataframe['Country'] == 'Kuwait', 'Region'] = 'Middle East and Northern Africa'
    target_dataframe.loc[target_dataframe['Country'] == 'Suriname', 'Region'] = 'Latin America and Caribbean'
    target_dataframe.loc[target_dataframe['Country'] == 'Trinidad and Tobago', 'Region'] = 'Latin America and Caribbean'
    target_dataframe.loc[target_dataframe['Country'] == 'Trinidad & Tobago', 'Region'] = 'Latin America and Caribbean' #
    target_dataframe.loc[target_dataframe['Country'] == 'El Salvador', 'Region'] = 'Latin America and Caribbean'
    target_dataframe.loc[target_dataframe['Country'] == 'Guatemala', 'Region'] = 'Latin America and Caribbean'
    target_dataframe.loc[target_dataframe['Country'] == 'Uzbekistan', 'Region'] = 'Central and Eastern Europe'
    target_dataframe.loc[target_dataframe['Country'] == 'Slovakia', 'Region'] = 'Central and Eastern Europe'
    target_dataframe.loc[target_dataframe['Country'] == 'Japan', 'Region'] = 'Eastern Asia'
    target_dataframe.loc[target_dataframe['Country'] == 'South Korea', 'Region'] = 'Eastern Asia'
    target_dataframe.loc[target_dataframe['Country'] == 'Ecuador', 'Region'] = 'Latin America and Caribbean'
    target_dataframe.loc[target_dataframe['Country'] == 'Bahrain', 'Region'] = 'Middle East and Northern Africa'
    target_dataframe.loc[target_dataframe['Country'] == 'Italy', 'Region'] = 'Western Europe'
    target_dataframe.loc[target_dataframe['Country'] == 'Bolivia', 'Region'] = 'Latin America and Caribbean'
    target_dataframe.loc[target_dataframe['Country'] == 'Moldova', 'Region'] = 'Central and Eastern Europe'
    target_dataframe.loc[target_dataframe['Country'] == 'Paraguay', 'Region'] = 'Latin America and Caribbean'
    target_dataframe.loc[target_dataframe['Country'] == 'Kazakhstan', 'Region'] = 'Central and Eastern Europe'
    target_dataframe.loc[target_dataframe['Country'] == 'Slovenia', 'Region'] = 'Central and Eastern Europe'
    target_dataframe.loc[target_dataframe['Country'] == 'Lithuania', 'Region'] = 'Central and Eastern Europe'
    target_dataframe.loc[target_dataframe['Country'] == 'Nicaragua', 'Region'] = 'Latin America and Caribbean'
    target_dataframe.loc[target_dataframe['Country'] == 'Peru', 'Region'] = 'Latin America and Caribbean'
    target_dataframe.loc[target_dataframe['Country'] == 'Belarus', 'Region'] = 'Central and Eastern Europe'
    target_dataframe.loc[target_dataframe['Country'] == 'Poland', 'Region'] = 'Central and Eastern Europe'
    target_dataframe.loc[target_dataframe['Country'] == 'Malaysia', 'Region'] = 'Southeastern Asia'
    target_dataframe.loc[target_dataframe['Country'] == 'Croatia', 'Region'] = 'Central and Eastern Europe'
    target_dataframe.loc[target_dataframe['Country'] == 'Libya', 'Region'] = 'Middle East and Northern Africa'
    target_dataframe.loc[target_dataframe['Country'] == 'Russia', 'Region'] = 'Central and Eastern Europe'
    target_dataframe.loc[target_dataframe['Country'] == 'Jamaica', 'Region'] = 'Latin America and Caribbean'
    target_dataframe.loc[target_dataframe['Country'] == 'North Cyprus', 'Region'] = 'Western Europe'
    target_dataframe.loc[target_dataframe['Country'] == 'Northern Cyprus', 'Region'] = 'Western Europe' #
    target_dataframe.loc[target_dataframe['Country'] == 'Cyprus', 'Region'] = 'Western Europe'
    target_dataframe.loc[target_dataframe['Country'] == 'Algeria', 'Region'] = 'Middle East and Northern Africa'
    target_dataframe.loc[target_dataframe['Country'] == 'Kosovo', 'Region'] = 'Central and Eastern Europe'
    target_dataframe.loc[target_dataframe['Country'] == 'Turkmenistan', 'Region'] = 'Central and Eastern Europe'
    target_dataframe.loc[target_dataframe['Country'] == 'Mauritius', 'Region'] = 'Sub-Saharan Africa'
    target_dataframe.loc[target_dataframe['Country'] == 'Hong Kong', 'Region'] = 'Eastern Asia'
    target_dataframe.loc[target_dataframe['Country'] == 'Estonia', 'Region'] = 'Central and Eastern Europe'
    target_dataframe.loc[target_dataframe['Country'] == 'Indonesia', 'Region'] = 'Southeastern Asia'
    target_dataframe.loc[target_dataframe['Country'] == 'Vietnam', 'Region'] = 'Southeastern Asia'
    target_dataframe.loc[target_dataframe['Country'] == 'Turkey', 'Region'] = 'Middle East and Northern Africa'
    target_dataframe.loc[target_dataframe['Country'] == 'Kyrgyzstan', 'Region'] = 'Central and Eastern Europe'
    target_dataframe.loc[target_dataframe['Country'] == 'Nigeria', 'Region'] = 'Sub-Saharan Africa'
    target_dataframe.loc[target_dataframe['Country'] == 'Bhutan', 'Region'] = 'Southern Asia'
    target_dataframe.loc[target_dataframe['Country'] == 'Azerbaijan', 'Region'] = 'Central and Eastern Europe'
    target_dataframe.loc[target_dataframe['Country'] == 'Pakistan', 'Region'] = 'Southern Asia'
    target_dataframe.loc[target_dataframe['Country'] == 'Jordan', 'Region'] = 'Middle East and Northern Africa'
    target_dataframe.loc[target_dataframe['Country'] == 'Montenegro', 'Region'] = 'Central and Eastern Europe'
    target_dataframe.loc[target_dataframe['Country'] == 'China', 'Region'] = 'Eastern Asia'
    target_dataframe.loc[target_dataframe['Country'] == 'Hong Kong S.A.R., China', 'Region'] = 'Eastern Asia' #
    target_dataframe.loc[target_dataframe['Country'] == 'Taiwan Province of China', 'Region'] = 'Eastern Asia' #
    target_dataframe.loc[target_dataframe['Country'] == 'Zambia', 'Region'] = 'Sub-Saharan Africa'
    target_dataframe.loc[target_dataframe['Country'] == 'Romania', 'Region'] = 'Central and Eastern Europe'
    target_dataframe.loc[target_dataframe['Country'] == 'Serbia', 'Region'] = 'Central and Eastern Europe'
    target_dataframe.loc[target_dataframe['Country'] == 'North Macedonia', 'Region'] = 'Central and Eastern Europe' #
    target_dataframe.loc[target_dataframe['Country'] == 'Portugal', 'Region'] = 'Western Europe'
    target_dataframe.loc[target_dataframe['Country'] == 'Latvia', 'Region'] = 'Central and Eastern Europe'
    target_dataframe.loc[target_dataframe['Country'] == 'Philippines', 'Region'] = 'Southeastern Asia'
    target_dataframe.loc[target_dataframe['Country'] == 'Somaliland region', 'Region'] = 'Sub-Saharan Africa'
    target_dataframe.loc[target_dataframe['Country'] == 'Morocco', 'Region'] = 'Middle East and Northern Africa'
    target_dataframe.loc[target_dataframe['Country'] == 'Macedonia', 'Region'] = 'Central and Eastern Europe'
    target_dataframe.loc[target_dataframe['Country'] == 'Mozambique', 'Region'] = 'Sub-Saharan Africa'
    target_dataframe.loc[target_dataframe['Country'] == 'Albania', 'Region'] = 'Central and Eastern Europe'
    target_dataframe.loc[target_dataframe['Country'] == 'Bosnia and Herzegovina', 'Region'] = 'Central and Eastern Europe'
    target_dataframe.loc[target_dataframe['Country'] == 'Lesotho', 'Region'] = 'Sub-Saharan Africa'
    target_dataframe.loc[target_dataframe['Country'] == 'Dominican Republic', 'Region'] = 'Latin America and Caribbean'
    target_dataframe.loc[target_dataframe['Country'] == 'Laos', 'Region'] = 'Southeastern Asia'
    target_dataframe.loc[target_dataframe['Country'] == 'Mongolia', 'Region'] = 'Eastern Asia'
    target_dataframe.loc[target_dataframe['Country'] == 'Swaziland', 'Region'] = 'Sub-Saharan Africa'
    target_dataframe.loc[target_dataframe['Country'] == 'Greece', 'Region'] = 'Western Europe'
    target_dataframe.loc[target_dataframe['Country'] == 'Lebanon', 'Region'] = 'Middle East and Northern Africa'
    target_dataframe.loc[target_dataframe['Country'] == 'Hungary', 'Region'] = 'Central and Eastern Europe'
    target_dataframe.loc[target_dataframe['Country'] == 'Honduras', 'Region'] = 'Latin America and Caribbean'
    target_dataframe.loc[target_dataframe['Country'] == 'Tajikistan', 'Region'] = 'Central and Eastern Europe'
    target_dataframe.loc[target_dataframe['Country'] == 'Tunisia', 'Region'] = 'Middle East and Northern Africa'
    target_dataframe.loc[target_dataframe['Country'] == 'Palestinian Territories', 'Region'] = 'Middle East and Northern Africa'
    target_dataframe.loc[target_dataframe['Country'] == 'Bangladesh', 'Region'] = 'Southern Asia'
    target_dataframe.loc[target_dataframe['Country'] == 'Iran', 'Region'] = 'Middle East and Northern Africa'
    target_dataframe.loc[target_dataframe['Country'] == 'Ukraine', 'Region'] = 'Central and Eastern Europe'
    target_dataframe.loc[target_dataframe['Country'] == 'Iraq', 'Region'] = 'Middle East and Northern Africa'
    target_dataframe.loc[target_dataframe['Country'] == 'South Africa', 'Region'] = 'Sub-Saharan Africa'
    target_dataframe.loc[target_dataframe['Country'] == 'Ghana', 'Region'] = 'Sub-Saharan Africa'
    target_dataframe.loc[target_dataframe['Country'] == 'Zimbabwe', 'Region'] = 'Sub-Saharan Africa'
    target_dataframe.loc[target_dataframe['Country'] == 'Liberia', 'Region'] = 'Sub-Saharan Africa'
    target_dataframe.loc[target_dataframe['Country'] == 'India', 'Region'] = 'Southern Asia'
    target_dataframe.loc[target_dataframe['Country'] == 'Sudan', 'Region'] = 'Sub-Saharan Africa'
    target_dataframe.loc[target_dataframe['Country'] == 'Haiti', 'Region'] = 'Latin America and Caribbean'
    target_dataframe.loc[target_dataframe['Country'] == 'Congo (Kinshasa)', 'Region'] = 'Sub-Saharan Africa'
    target_dataframe.loc[target_dataframe['Country'] == 'Nepal', 'Region'] = 'Southern Asia'
    target_dataframe.loc[target_dataframe['Country'] == 'Ethiopia', 'Region'] = 'Sub-Saharan Africa'
    target_dataframe.loc[target_dataframe['Country'] == 'Sierra Leone', 'Region'] = 'Sub-Saharan Africa'
    target_dataframe.loc[target_dataframe['Country'] == 'Mauritania', 'Region'] = 'Sub-Saharan Africa'
    target_dataframe.loc[target_dataframe['Country'] == 'Kenya', 'Region'] = 'Sub-Saharan Africa'
    target_dataframe.loc[target_dataframe['Country'] == 'Djibouti', 'Region'] = 'Sub-Saharan Africa'
    target_dataframe.loc[target_dataframe['Country'] == 'Armenia', 'Region'] = 'Central and Eastern Europe'
    target_dataframe.loc[target_dataframe['Country'] == 'Botswana', 'Region'] = 'Sub-Saharan Africa'
    target_dataframe.loc[target_dataframe['Country'] == 'Myanmar', 'Region'] = 'Southeastern Asia'
    target_dataframe.loc[target_dataframe['Country'] == 'Georgia', 'Region'] = 'Central and Eastern Europe'
    target_dataframe.loc[target_dataframe['Country'] == 'Malawi', 'Region'] = 'Sub-Saharan Africa'
    target_dataframe.loc[target_dataframe['Country'] == 'Sri Lanka', 'Region'] = 'Southern Asia'
    target_dataframe.loc[target_dataframe['Country'] == 'Cameroon', 'Region'] = 'Sub-Saharan Africa'
    target_dataframe.loc[target_dataframe['Country'] == 'Bulgaria', 'Region'] = 'Central and Eastern Europe'
    target_dataframe.loc[target_dataframe['Country'] == 'Egypt', 'Region'] = 'Middle East and Northern Africa'
    target_dataframe.loc[target_dataframe['Country'] == 'Yemen', 'Region'] = 'Middle East and Northern Africa'
    target_dataframe.loc[target_dataframe['Country'] == 'Angola', 'Region'] = 'Sub-Saharan Africa'
    target_dataframe.loc[target_dataframe['Country'] == 'Mali', 'Region'] = 'Sub-Saharan Africa'
    target_dataframe.loc[target_dataframe['Country'] == 'Congo (Brazzaville)', 'Region'] = 'Sub-Saharan Africa'
    target_dataframe.loc[target_dataframe['Country'] == 'Comoros', 'Region'] = 'Sub-Saharan Africa'
    target_dataframe.loc[target_dataframe['Country'] == 'Uganda', 'Region'] = 'Sub-Saharan Africa'
    target_dataframe.loc[target_dataframe['Country'] == 'Senegal', 'Region'] = 'Sub-Saharan Africa'
    target_dataframe.loc[target_dataframe['Country'] == 'Gabon', 'Region'] = 'Sub-Saharan Africa'
    target_dataframe.loc[target_dataframe['Country'] == 'Niger', 'Region'] = 'Sub-Saharan Africa'
    target_dataframe.loc[target_dataframe['Country'] == 'Cambodia', 'Region'] = 'Southeastern Asia'
    target_dataframe.loc[target_dataframe['Country'] == 'Tanzania', 'Region'] = 'Sub-Saharan Africa'
    target_dataframe.loc[target_dataframe['Country'] == 'Madagascar', 'Region'] = 'Sub-Saharan Africa'
    target_dataframe.loc[target_dataframe['Country'] == 'Central African Republic', 'Region'] = 'Sub-Saharan Africa'
    target_dataframe.loc[target_dataframe['Country'] == 'Chad', 'Region'] = 'Sub-Saharan Africa'
    target_dataframe.loc[target_dataframe['Country'] == 'Guinea', 'Region'] = 'Sub-Saharan Africa'
    target_dataframe.loc[target_dataframe['Country'] == 'Ivory Coast', 'Region'] = 'Sub-Saharan Africa'
    target_dataframe.loc[target_dataframe['Country'] == 'Burkina Faso', 'Region'] = 'Sub-Saharan Africa'
    target_dataframe.loc[target_dataframe['Country'] == 'Afghanistan', 'Region'] = 'Southern Asia'
    target_dataframe.loc[target_dataframe['Country'] == 'Rwanda', 'Region'] = 'Sub-Saharan Africa'
    target_dataframe.loc[target_dataframe['Country'] == 'Benin', 'Region'] = 'Sub-Saharan Africa'
    target_dataframe.loc[target_dataframe['Country'] == 'Syria', 'Region'] = 'Middle East and Northern Africa'
    target_dataframe.loc[target_dataframe['Country'] == 'Burundi', 'Region'] = 'Sub-Saharan Africa'
    target_dataframe.loc[target_dataframe['Country'] == 'Togo', 'Region'] = 'Sub-Saharan Africa'
    target_dataframe.loc[target_dataframe['Country'] == 'Namibia', 'Region'] = 'Sub-Saharan Africa' #
    target_dataframe.loc[target_dataframe['Country'] == 'Gambia', 'Region'] = 'Sub-Saharan Africa' #
    target_dataframe.loc[target_dataframe['Country'] == 'South Sudan', 'Region'] = 'Sub-Saharan Africa' #
    target_dataframe.loc[target_dataframe['Country'] == 'Somalia', 'Region'] = 'Sub-Saharan Africa' #
